apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do sleep 10; done']
    volumeMounts:
    - name: configmap-volume
      mountPath: /k8s/config/configmap
    - name: secret-volume
      mountPath: /k8s/secret/secret
  volumes:
  - name: configmap-volume
    configMap:
      name: my-config
  - name: secret-volume
    secret:
      secretName: my-secret