apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo configmap is: $CONFIGMAPVAR && sleep 3600']
    env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: name