apiVersion: apps/v1
kind: Deployment
metadata:
  name: rol-deploy
spec:
  template:
    metadata:
      name: rol-pod
      labels:
        type: rol
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 2
  selector:
    matchLabels:
      type: rol
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2